### ISSUE TITLE
Bionic Reading® Legal Stuff

### ISSUE THREAD

**Issue by jomamaaye** [Cveinnt/bionify#1]
This isn't a bug, but I just want to inform y'all that the wonderful® folks at Bionic Reading® have decided to crack down on any open source projects that involves Bionic Reading®. It is advised to remove all mentioning of Bionic Reading® for now to avoid legal repercussions.

Context
<img width="746" alt="legal notice" src="https://user-images.githubusercontent.com/106170863/171383202-130509cf-decc-4c6c-808e-710023746358.png">

**Comment by Cveinnt** [comment]
Thanks for letting me know - I'll update the extension accordingly.
