### ISSUE TITLE
XSS Vulnerability

### ISSUE THREAD

**Issue by user8446** [Cveinnt/bionify#4]
Hi,

If you didn't know already, there is a XSS Vuln and mitigation found in fastread to add to bionify:

https://github.com/ahrm/chrome-fastread/issues/10

Thank you for maintaining bionify!

**Comment by Cveinnt** [comment]
@user8446 thanks for mentioning this. I proposed the current fix and pushed it to fastread, and Bionify comes with the fix already. Though if anyone has a better solution, feel free to contribute to it!
